---
displaymanagers:
  - sddm
defaultDesktopEnvironment:
    executable: "startplasma-x11"
    desktopFile: "plasma"   # в Plasma 5 (Ubuntu 24.04) это сеанс X11
basicSetup: false
sysconfigSetup: false
